config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  resources :product_stocks
  root "products#index"
  resources :products
  resources :stocks
  resources :users
  resources :stocks do
    resources :products do
      get 'edit', to: 'product_stocks#edit'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  has_many :product_stocks
  has_many :stocks, through: :product_stocks

  belongs_to :user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  #before_filter :authenticate_user!, except => [:new, :create, :destroy, :update]
  before_action :authenticate_user!, only: %i[show new create edit destroy update edit_amount]
  load_and_authorize_resource
  # GET /products or /products.json
  def index
    if params[:search].blank? and params[:stock_ids].blank?
      @products = Product.all
    elsif params[:stock_ids].present?
      @products = Product.where(id: ProductStock.where('amount != 0').where(stock_id: params[:stock_ids].map(&:to_i)).pluck(:product_id))
    else
      key = "%#{params[:search]}%"
      @products = Product.where("title LIKE ?", key)
    end
    @stocks = Stock.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end


  # POST /products or /products.json
  def create
    @product = Product.new(title: product_params['title'], body: product_params['body'], user_id: current_user.id)
    Stock.all.each do |stock|
      @product.stocks << stock
    end
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.stocks.destroy_all
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :body)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Название, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :Описание, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit(class: 'btn btn-dark') %>
  </div>
<% end %>

app/views/products/_form_amount.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? or stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Title:</strong>
    <%= product.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= product.body %>
  </p>

</div>

app/views/products/edit.html.erb
<div class="row mt-5 justify-content-center ">
  <div class="col-xl-2 col-md-4 d-flex align-items-stretch update_product">
    <div class="w-100 p-3">
      <h1>Изменение товара</h1>

    <%= render "form", product: @product %>
    <%= link_to "Показать этот товар", @product %>
    </div>
  </div>
</div>

app/views/products/edit_amount.html.erb
<h1>Editing product</h1>

<%= render "form_amount", product: @product, stock: @stock %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/new.html.erb
<div class="row mt-5 justify-content-center ">
  <div class="col-xl-2 col-md-4 d-flex align-items-stretch update_product">
    <div class="w-100 p-3">
      <h1>Новый товар</h1>
<%= render "form", product: @product %>
    </div>
  </div>
</div>
<br>